// Shared deliverable helpers: copy, download (JSON / Markdown), and print-to-PDF.

export async function copyText(text) {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (_) {
    // Fallback for insecure contexts.
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      return true;
    } catch (_e) {
      return false;
    }
  }
}

export function downloadBlob(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadJSON(filename, data) {
  downloadBlob(filename.endsWith('.json') ? filename : `${filename}.json`, JSON.stringify(data, null, 2), 'application/json');
}

export function downloadMarkdown(filename, markdown) {
  downloadBlob(filename.endsWith('.md') ? filename : `${filename}.md`, markdown, 'text/markdown');
}

const slug = (s) => String(s || 'deliverable').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);

export function fileName(title, ext) {
  return `${slug(title)}-${Date.now()}.${ext}`;
}

// Build a readable Markdown doc from a titled list of { label, detail } items,
// or from an arbitrary object of section -> value.
export function toMarkdown(title, sections) {
  const lines = [`# ${title}`, ''];
  const push = (heading, body) => {
    lines.push(`## ${heading}`, '');
    if (Array.isArray(body)) {
      body.forEach((b) => lines.push(`- ${b}`));
    } else if (body && typeof body === 'object') {
      Object.entries(body).forEach(([k, v]) => lines.push(`- **${k}:** ${Array.isArray(v) ? v.join(', ') : v}`));
    } else if (body != null) {
      lines.push(String(body));
    }
    lines.push('');
  };
  if (Array.isArray(sections)) {
    sections.forEach((s) => push(s.label || s.title || 'Section', s.detail ?? s.value ?? s.items ?? ''));
  } else if (sections && typeof sections === 'object') {
    Object.entries(sections).forEach(([k, v]) => push(k, v));
  }
  return lines.join('\n');
}

// Print a specific element (or the full doc) using a clean print window.
export function printHTML(title, innerHTML) {
  const w = window.open('', '_blank', 'width=880,height=1000');
  if (!w) return false;
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
    <style>
      *{box-sizing:border-box}
      body{font-family:Georgia,'Times New Roman',serif;color:#111;line-height:1.55;max-width:720px;margin:40px auto;padding:0 24px}
      h1{font-size:28px;margin:0 0 4px;border-bottom:2px solid #b8892b;padding-bottom:10px}
      h2{font-size:18px;margin:26px 0 8px;color:#9a6f1f}
      h3{font-size:15px;margin:18px 0 4px}
      p,li{font-size:13.5px}
      ul{padding-left:20px}
      .meta{color:#666;font-size:12px;font-family:Arial,sans-serif;margin-bottom:24px}
      .item{margin:10px 0;padding:10px 14px;border:1px solid #e2e2e2;border-radius:8px;page-break-inside:avoid}
      .item .label{font-weight:bold}
      @media print{body{margin:0}}
    </style></head><body>
    <div class="meta">Generated by Wyzrdy · ${new Date().toLocaleString()}</div>
    ${innerHTML}
    </body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => { try { w.print(); } catch (_) { /* ignore */ } }, 350);
  return true;
}
